# Generated by Django 4.2.6 on 2023-10-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posttable_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttable',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
