# Generated by Django 4.2.6 on 2023-10-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_posttable_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttable',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
