# Generated by Django 4.2.6 on 2023-10-23 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_posttable_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttable',
            name='item',
        ),
        migrations.AddField(
            model_name='posttable',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.list'),
        ),
    ]
