# Generated by Django 4.2.6 on 2023-10-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_actor_posttable_actros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filmname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Filmphoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='posttable',
            name='filmnames',
            field=models.ManyToManyField(to='blog.filmname'),
        ),
        migrations.AddField(
            model_name='posttable',
            name='filmphotos',
            field=models.ManyToManyField(to='blog.filmphoto'),
        ),
    ]
