# Generated by Django 4.2.6 on 2023-10-31 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Registerform',
        ),
    ]
