# Generated by Django 4.2.6 on 2023-11-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_rename_firstname_registerform_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvtable',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
